use serde::{Serialize, Deserialize};
use crate::types::{ChunkHash, FileHash};

/// Type of shard within an erasure coding group
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ShardType {
    /// Original data shard
    Data,
    /// Parity shard generated by Reed-Solomon
    Parity,
}

/// Erasure coding configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErasureConfig {
    /// Number of data shards per group
    pub data_shards: u32,
    /// Number of parity shards per group
    pub parity_shards: u32,
}

impl ErasureConfig {
    pub fn rs_4_2() -> Self {
        Self { data_shards: 4, parity_shards: 2 }
    }

    pub fn total_shards(&self) -> u32 {
        self.data_shards + self.parity_shards
    }
}

/// Metadata for a single chunk/shard within a manifest
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkMeta {
    pub hash: ChunkHash,
    pub size: u32,
    pub index: u32,
    /// Erasure coding group index (chunks 0..3 in group 0, 4..7 in group 1, etc.)
    #[serde(default)]
    pub group_index: u32,
    /// Shard index within the erasure group (0..data_shards-1 = data, data_shards..total-1 = parity)
    #[serde(default)]
    pub shard_index: u32,
    /// Whether this is a data shard or parity shard
    #[serde(default = "default_shard_type")]
    pub shard_type: ShardType,
    /// Original data size before padding (shards in a group are padded to equal length)
    #[serde(default)]
    pub original_size: u32,
}

fn default_shard_type() -> ShardType {
    ShardType::Data
}

impl Default for ShardType {
    fn default() -> Self {
        ShardType::Data
    }
}

/// File manifest: describes how a file is chunked and how to reassemble it
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub file_hash: FileHash,
    pub file_name: String,
    pub file_size: u64,
    pub chunks: Vec<ChunkMeta>,
    /// Erasure coding config. None means no erasure coding (backward compat).
    #[serde(default)]
    pub erasure: Option<ErasureConfig>,
}

impl Manifest {
    pub fn total_chunks(&self) -> usize {
        self.chunks.len()
    }

    /// Get only the data chunks (excluding parity), sorted by index
    pub fn data_chunks(&self) -> Vec<&ChunkMeta> {
        let mut data: Vec<_> = self.chunks.iter()
            .filter(|c| c.shard_type == ShardType::Data)
            .collect();
        data.sort_by_key(|c| c.index);
        data
    }

    /// Get chunks for a specific erasure group
    pub fn group_chunks(&self, group_index: u32) -> Vec<&ChunkMeta> {
        self.chunks.iter()
            .filter(|c| c.group_index == group_index)
            .collect()
    }

    /// Number of erasure groups
    pub fn group_count(&self) -> u32 {
        self.chunks.iter()
            .map(|c| c.group_index)
            .max()
            .map(|m| m + 1)
            .unwrap_or(0)
    }

    /// Convert to protobuf ManifestPush message
    pub fn to_proto_push(&self) -> ldrive_proto::ManifestPush {
        ldrive_proto::ManifestPush {
            file_hash: self.file_hash.0.to_vec(),
            file_name: self.file_name.clone(),
            file_size: self.file_size,
            chunks: self.chunks.iter().map(|c| ldrive_proto::ChunkInfo {
                hash: c.hash.0.to_vec(),
                size: c.size,
                index: c.index,
                group_index: c.group_index,
                shard_index: c.shard_index,
                is_parity: c.shard_type == ShardType::Parity,
                original_size: c.original_size,
            }).collect(),
            erasure_data_shards: self.erasure.as_ref().map(|e| e.data_shards).unwrap_or(0),
            erasure_parity_shards: self.erasure.as_ref().map(|e| e.parity_shards).unwrap_or(0),
        }
    }

    /// Parse from protobuf ManifestPush message
    pub fn from_proto_push(msg: &ldrive_proto::ManifestPush) -> Option<Self> {
        let file_hash = FileHash::from_bytes(&msg.file_hash)?;
        let chunks = msg.chunks.iter().filter_map(|c| {
            Some(ChunkMeta {
                hash: ChunkHash::from_bytes(&c.hash)?,
                size: c.size,
                index: c.index,
                group_index: c.group_index,
                shard_index: c.shard_index,
                shard_type: if c.is_parity { ShardType::Parity } else { ShardType::Data },
                original_size: c.original_size,
            })
        }).collect::<Vec<_>>();

        if chunks.len() != msg.chunks.len() {
            return None;
        }

        let erasure = if msg.erasure_data_shards > 0 {
            Some(ErasureConfig {
                data_shards: msg.erasure_data_shards,
                parity_shards: msg.erasure_parity_shards,
            })
        } else {
            None
        };

        Some(Self {
            file_hash,
            file_name: msg.file_name.clone(),
            file_size: msg.file_size,
            chunks,
            erasure,
        })
    }

    /// Serialize to bytes (JSON)
    pub fn to_bytes(&self) -> Vec<u8> {
        serde_json::to_vec(self).expect("manifest serialization should not fail")
    }

    /// Deserialize from bytes
    pub fn from_bytes(bytes: &[u8]) -> Option<Self> {
        serde_json::from_slice(bytes).ok()
    }
}
